// <auto-generated />
using System;
using DVR_RAMP_Company.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DVR_RAMP_Company.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230326163005_Ramp_to_BD")]
    partial class Ramp_to_BD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.2.23128.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DVR_RAMP_Company.Model.Tb_Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PRD_Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRD_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PRD_Date_Launched")
                        .HasColumnType("date");

                    b.Property<byte[]>("PRD_Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PRD_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PRD_Price")
                        .HasColumnType("int");

                    b.Property<string>("PRD_SubBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tb_Product");
                });

            modelBuilder.Entity("DVR_RAMP_Company.Model.Tb_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Rep_Code")
                        .HasColumnType("int");

                    b.Property<string>("Rep_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rep_Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tb_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
